import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  snacksNdMunchies = {
    title: 'Snacks & munchies',
    products: [
      {
        id: 1,
        name: 'Lays',
        quantity: 1,
        price: 50,
        reviews: 5,
        averageReviews: 4.5,
        availability: 'IN_STOCK',
        imageSrc: '/images/lays.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 2,
        name: 'Bingo',
        quantity: 1,
        price: 45,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/bingo.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 3,
        name: 'Pringles',
        quantity: 1,
        price: 150,
        reviews: 5,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/pringles.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 4,
        name: 'Too Yum',
        quantity: 1,
        price: 35,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/too-yum.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 5,
        name: 'Marie Gold',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.0,
        availability: 'IN_STOCK',
        imageSrc: '/images/marie-gold.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 6,
        name: 'Bourbon',
        quantity: 1,
        price: 40,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/bourbon.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 7,
        name: 'Dark Fantasy',
        quantity: 1,
        price: 70,
        reviews: 5,
        averageReviews: 4.8,
        availability: 'IN_STOCK',
        imageSrc: '/images/dark-fantasy.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 8,
        name: 'Oreo',
        quantity: 1,
        price: 35,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/oreo.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 9,
        name: 'Hide & Seek',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/hide-and-seek.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 10,
        name: 'Good Day',
        quantity: 1,
        price: 35,
        reviews: 4,
        averageReviews: 4.1,
        availability: 'IN_STOCK',
        imageSrc: '/images/good-day.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 11,
        name: 'Unibic',
        quantity: 1,
        price: 50,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/unibic.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 12,
        name: 'Happy Happy',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/happy-happy.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 13,
        name: 'Little Hearts',
        quantity: 1,
        price: 20,
        reviews: 4,
        averageReviews: 4.0,
        availability: 'IN_STOCK',
        imageSrc: '/images/little-hearts.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 14,
        name: 'Dairy Milk',
        quantity: 1,
        price: 50,
        reviews: 5,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/dairy-milk.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 15,
        name: 'Bournville',
        quantity: 1,
        price: 120,
        reviews: 5,
        averageReviews: 4.6,
        availability: 'IN_STOCK',
        imageSrc: '/images/bournville.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 16,
        name: 'Dairy Milk Silk',
        quantity: 1,
        price: 90,
        reviews: 5,
        averageReviews: 4.8,
        availability: 'IN_STOCK',
        imageSrc: '/images/dairy-milk-silk.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 17,
        name: 'Milkybar',
        quantity: 1,
        price: 50,
        reviews: 4,
        averageReviews: 4.4,
        availability: 'IN_STOCK',
        imageSrc: '/images/milkybar.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 18,
        name: '5 Star',
        quantity: 1,
        price: 10,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/5-star.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 19,
        name: 'Kit Kat',
        quantity: 1,
        price: 20,
        reviews: 5,
        averageReviews: 4.5,
        availability: 'IN_STOCK',
        imageSrc: '/images/kit-kat.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
      {
        id: 20,
        name: 'Ferrero Rocher',
        quantity: 1,
        price: 400,
        reviews: 5,
        averageReviews: 4.9,
        availability: 'IN_STOCK',
        imageSrc: '/images/ferrero-rocher.jpg',
        isAddedToFav: false,
        category: 'snacksNdMunchies',
      },
    ],
  };

  fruitsNdVegetables = {
    title: 'Fruits & vegetables',
    products: [
      {
        id: 21,
        name: 'Kiwi',
        quantity: 1,
        price: 120,
        reviews: 5,
        averageReviews: 4.6,
        availability: 'IN_STOCK',
        imageSrc: '/images/kiwi.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 22,
        name: 'Dragon Fruit',
        quantity: 1,
        price: 150,
        reviews: 5,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/dragon-fruit.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 23,
        name: 'Papaya',
        quantity: 1,
        price: 50,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/papaya.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 24,
        name: 'Banana',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.1,
        availability: 'IN_STOCK',
        imageSrc: '/images/banana.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 25,
        name: 'Watermelon',
        quantity: 1,
        price: 100,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/watermelon.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 26,
        name: 'Oranges',
        quantity: 1,
        price: 70,
        reviews: 5,
        averageReviews: 4.6,
        availability: 'IN_STOCK',
        imageSrc: '/images/oranges.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 27,
        name: 'Apples',
        quantity: 1,
        price: 120,
        reviews: 5,
        averageReviews: 4.8,
        availability: 'IN_STOCK',
        imageSrc: '/images/apples.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 28,
        name: 'Pomegranate',
        quantity: 1,
        price: 150,
        reviews: 5,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/pomegranates.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 29,
        name: 'Lemon',
        quantity: 1,
        price: 15,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/lemons.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 30,
        name: 'Coconut',
        quantity: 1,
        price: 35,
        reviews: 12,
        averageReviews: 4.5,
        availability: 'IN_STOCK',
        imageSrc: '/images/coconut.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 31,
        name: 'Capsicum',
        quantity: 1,
        price: 40,
        reviews: 4,
        averageReviews: 4.1,
        availability: 'IN_STOCK',
        imageSrc: '/images/capsicum.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 32,
        name: 'Gongura Leaves',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/gongura-leaves.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 32,
        name: 'Cabbage',
        quantity: 1,
        price: 20,
        reviews: 4,
        averageReviews: 4.0,
        availability: 'IN_STOCK',
        imageSrc: '/images/cabbage.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 33,
        name: 'Lady Fingers',
        quantity: 1,
        price: 25,
        reviews: 4,
        averageReviews: 4.1,
        availability: 'IN_STOCK',
        imageSrc: '/images/lady-fingers.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 34,
        name: 'Cauli Flower',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/cauli-flower.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 35,
        name: 'Green Chillies',
        quantity: 1,
        price: 10,
        reviews: 4,
        averageReviews: 4.1,
        availability: 'IN_STOCK',
        imageSrc: '/images/green-chillies.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 36,
        name: 'Onions',
        quantity: 1,
        price: 40,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/onions.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 37,
        name: 'Tomatoes',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/tomatoes.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 38,
        name: 'Cucumber',
        quantity: 1,
        price: 20,
        reviews: 4,
        averageReviews: 4.0,
        availability: 'IN_STOCK',
        imageSrc: '/images/cucumber.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 39,
        name: 'Potatoes',
        quantity: 1,
        price: 40,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/potatoes.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 40,
        name: 'Beetroot',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.1,
        availability: 'IN_STOCK',
        imageSrc: '/images/beetroot.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 41,
        name: 'Carrots',
        quantity: 1,
        price: 50,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/carrots.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
      {
        id: 42,
        name: 'Ginger',
        quantity: 1,
        price: 10,
        reviews: 9,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/ginger.jpg',
        isAddedToFav: false,
        category: 'fruitsNdVegetables',
      },
    ],
  };

  diaryProducts = {
    title: 'Dairy Products',
    products: [
      {
        id: 43,
        name: 'Ghee',
        quantity: 1,
        price: 400,
        reviews: 5,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/ghee.jpg',
        isAddedToFav: false,
        category: 'diaryProducts',
      },
      {
        id: 44,
        name: 'Paneer',
        quantity: 1,
        price: 200,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/paneer.jpg',
        isAddedToFav: false,
        category: 'diaryProducts',
      },
      {
        id: 45,
        name: 'Eggs',
        quantity: 1,
        price: 60,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/eggs.jpg',
        isAddedToFav: false,
        category: 'diaryProducts',
      },
      {
        id: 46,
        name: 'Yogurt',
        quantity: 1,
        price: 50,
        reviews: 4,
        averageReviews: 4.0,
        availability: 'IN_STOCK',
        imageSrc: '/images/yogurt.jpg',
        isAddedToFav: false,
        category: 'diaryProducts',
      },
      {
        id: 47,
        name: 'Butter',
        quantity: 1,
        price: 80,
        reviews: 4,
        averageReviews: 4.4,
        availability: 'IN_STOCK',
        imageSrc: '/images/butter.jpg',
        isAddedToFav: false,
        category: 'diaryProducts',
      },
      {
        id: 48,
        name: 'Curd',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/curd.jpg',
        isAddedToFav: false,
        category: 'diaryProducts',
      },
      {
        id: 49,
        name: 'Cheese',
        quantity: 1,
        price: 100,
        reviews: 5,
        averageReviews: 4.6,
        availability: 'IN_STOCK',
        imageSrc: '/images/cheese.jpg',
        isAddedToFav: false,
        category: 'diaryProducts',
      },
    ],
  };

  drinksNdJuices = {
    title: 'Drinks & juices',
    products: [
      {
        id: 50,
        name: 'Tang',
        quantity: 1,
        price: 90,
        reviews: 4,
        averageReviews: 4.4,
        availability: 'IN_STOCK',
        imageSrc: '/images/tang.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
      {
        id: 51,
        name: 'Red Bull',
        quantity: 1,
        price: 120,
        reviews: 5,
        averageReviews: 4.6,
        availability: 'IN_STOCK',
        imageSrc: '/images/red-bull.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
      {
        id: 52,
        name: 'Pulpy Orange',
        quantity: 1,
        price: 60,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/pulpy-orange.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
      {
        id: 53,
        name: '7Up',
        quantity: 1,
        price: 40,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/7-up.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
      {
        id: 54,
        name: 'Club Soda',
        quantity: 1,
        price: 30,
        reviews: 4,
        averageReviews: 4.1,
        availability: 'IN_STOCK',
        imageSrc: '/images/club-soda.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
      {
        id: 55,
        name: 'Thums Up',
        quantity: 1,
        price: 40,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/thums-up.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
      {
        id: 56,
        name: 'Coca Cola',
        quantity: 1,
        price: 40,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/cocacola.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
      {
        id: 57,
        name: 'Mirinda',
        quantity: 1,
        price: 40,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'IN_STOCK',
        imageSrc: '/images/mirinda.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
      {
        id: 58,
        name: 'Slice',
        quantity: 1,
        price: 50,
        reviews: 4,
        averageReviews: 4.4,
        availability: 'IN_STOCK',
        imageSrc: '/images/slice.jpg',
        isAddedToFav: false,
        category: 'drinksNdJuices',
      },
    ],
  };

  attaNdFlour = {
    title: 'Atta, Dal and Grams',
    products: [
      {
        id: 59,
        name: 'Ragi flour',
        quantity: 1,
        price: 200,
        reviews: 5,
        averageReviews: 4.8,
        availability: 'IN_STOCK',
        imageSrc: '/images/ragi-flour.jpg',
        isAddedToFav: false,
      },
      {
        id: 60,
        name: 'Toor Dal',
        quantity: 1,
        price: 150,
        reviews: 5,
        averageReviews: 4.5,
        availability: 'IN_STOCK',
        imageSrc: '/images/toor-dal.jpg',
        isAddedToFav: false,
      },
      {
        id: 61,
        name: 'Gram flour',
        quantity: 1,
        price: 120,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/gram-flour.jpg',
        isAddedToFav: false,
      },
      {
        id: 62,
        name: 'Rice flour',
        quantity: 1,
        price: 100,
        reviews: 5,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/rice-flour.jpg',
        isAddedToFav: false,
      },
      {
        id: 63,
        name: 'Wheat flour',
        quantity: 1,
        price: 80,
        reviews: 3,
        averageReviews: 3.9,
        availability: 'IN_STOCK',
        imageSrc: '/images/wheat-flour.jpg',
        isAddedToFav: false,
      },
      {
        id: 64,
        name: 'Brown rice',
        quantity: 1,
        price: 250,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'SOLD_OUT',
        imageSrc: '/images/brown-rice.jpg',
        isAddedToFav: false,
      },
      {
        id: 65,
        name: 'Soya beans',
        quantity: 1,
        price: 180,
        reviews: 2,
        averageReviews: 3.5,
        availability: 'IN_STOCK',
        imageSrc: '/images/soya-beans.jpg',
        isAddedToFav: false,
      },
      {
        id: 66,
        name: 'Basmathi rice',
        quantity: 1,
        price: 300,
        reviews: 5,
        averageReviews: 4.9,
        availability: 'IN_STOCK',
        imageSrc: '/images/basmathi-rice.jpg',
        isAddedToFav: false,
      },
      {
        id: 67,
        name: 'Bengal gram',
        quantity: 1,
        price: 90,
        reviews: 4,
        averageReviews: 4.1,
        availability: 'SOLD_OUT',
        imageSrc: '/images/bengal-gram.jpg',
        isAddedToFav: false,
      },
      {
        id: 68,
        name: 'Horse Gram',
        quantity: 1,
        price: 110,
        reviews: 3,
        averageReviews: 3.8,
        availability: 'IN_STOCK',
        imageSrc: '/images/horse-gram.jpg',
        isAddedToFav: false,
      },
      {
        id: 69,
        name: 'Rajma',
        quantity: 1,
        price: 160,
        reviews: 5,
        averageReviews: 4.6,
        availability: 'IN_STOCK',
        imageSrc: '/images/rajma.jpg',
        isAddedToFav: false,
      },
      {
        id: 70,
        name: 'Kabuli chana',
        quantity: 1,
        price: 140,
        reviews: 4,
        averageReviews: 4.3,
        availability: 'SOLD_OUT',
        imageSrc: '/images/kabuli-chana.jpg',
        isAddedToFav: false,
      },
      {
        id: 71,
        name: 'Moth Dal',
        quantity: 1,
        price: 130,
        reviews: 3,
        averageReviews: 3.9,
        availability: 'IN_STOCK',
        imageSrc: '/images/moth-dal.jpg',
        isAddedToFav: false,
      },
      {
        id: 72,
        name: 'Chana Dal',
        quantity: 1,
        price: 110,
        reviews: 2,
        averageReviews: 3.6,
        availability: 'IN_STOCK',
        imageSrc: '/images/chana-dal.jpg',
        isAddedToFav: false,
      },
      {
        id: 73,
        name: 'Masoor Dal',
        quantity: 1,
        price: 120,
        reviews: 4,
        averageReviews: 4.4,
        availability: 'SOLD_OUT',
        imageSrc: '/images/masoor-dal.jpg',
        isAddedToFav: false,
      },
      {
        id: 74,
        name: 'Urad Dal',
        quantity: 1,
        price: 130,
        reviews: 5,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/urad-dal.jpg',
        isAddedToFav: false,
      },
      {
        id: 75,
        name: 'Moong Dal Green',
        quantity: 1,
        price: 160,
        reviews: 4,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/moong-dal-green.jpg',
        isAddedToFav: false,
      },
    ],
  };

  nutsNdSeeds = {
    title: 'Nuts and Seeds',
    products: [
      {
        id: 76,
        name: 'Cashew',
        quantity: 1,
        price: 600,
        reviews: 3,
        averageReviews: 4.5,
        availability: 'IN_STOCK',
        imageSrc: '/images/cashew.jpg',
        isAddedToFav: false,
      },
      {
        id: 77,
        name: 'Hazel Nut',
        quantity: 1,
        price: 2000,
        reviews: 5,
        averageReviews: 4.8,
        availability: 'SOLD_OUT',
        imageSrc: '/images/hazelnut.jpg',
        isAddedToFav: false,
      },
      {
        id: 78,
        name: 'Walnut',
        quantity: 1,
        price: 450,
        reviews: 4,
        averageReviews: 4.6,
        availability: 'IN_STOCK',
        imageSrc: '/images/walnut.jpg',
        isAddedToFav: false,
      },
      {
        id: 79,
        name: 'Pistachios',
        quantity: 1,
        price: 660,
        reviews: 6,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/pistachios.jpg',
        isAddedToFav: false,
      },
      {
        id: 80,
        name: 'Brazil nut',
        quantity: 1,
        price: 760,
        reviews: 3,
        averageReviews: 4.4,
        availability: 'SOLD_OUT',
        imageSrc: '/images/brazilnut.jpg',
        isAddedToFav: false,
      },
      {
        id: 81,
        name: 'Sunflower seeds',
        quantity: 1,
        price: 330,
        reviews: 4,
        averageReviews: 4.5,
        availability: 'IN_STOCK',
        imageSrc: '/images/sunflower-seeds.jpg',
        isAddedToFav: false,
      },
      {
        id: 82,
        name: 'Pumpkin seeds',
        quantity: 1,
        price: 430,
        reviews: 5,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/pumpkin-seeds.jpg',
        isAddedToFav: false,
      },
      {
        id: 83,
        name: 'Hemp seeds',
        quantity: 1,
        price: 380,
        reviews: 4,
        averageReviews: 4.6,
        availability: 'SOLD_OUT',
        imageSrc: '/images/hemp-seeds.jpg',
        isAddedToFav: false,
      },
    ],
  };

  superFoods = {
    title: 'Super foods',
    products: [
      {
        id: 1,
        name: 'Blue berry',
        quantity: 84,
        price: 470,
        reviews: 5,
        averageReviews: 4.8,
        availability: 'IN_STOCK',
        imageSrc: '/images/dried-blue-berry.jpg',
        isAddedToFav: false,
      },
      {
        id: 2,
        name: 'Artichoke',
        quantity: 85,
        price: 120,
        reviews: 3,
        averageReviews: 4.0,
        availability: 'SOLD_OUT',
        imageSrc: '/images/artichoke.jpg',
        isAddedToFav: false,
      },
      {
        id: 3,
        name: 'Brussels sprouts',
        quantity: 86,
        price: 120,
        reviews: 4,
        averageReviews: 4.5,
        availability: 'IN_STOCK',
        imageSrc: '/images/brussels-sprouts.jpg',
        isAddedToFav: false,
      },
      {
        id: 4,
        name: 'Avocado',
        quantity: 87,
        price: 320,
        reviews: 6,
        averageReviews: 4.7,
        availability: 'IN_STOCK',
        imageSrc: '/images/avocado.jpg',
        isAddedToFav: false,
      },
      {
        id: 5,
        name: 'Broccoli',
        quantity: 88,
        price: 160,
        reviews: 5,
        averageReviews: 4.6,
        availability: 'SOLD_OUT',
        imageSrc: '/images/broccoli.jpg',
        isAddedToFav: false,
      },
      {
        id: 89,
        name: 'Quinoa seeds',
        quantity: 1,
        price: 165,
        reviews: 3,
        averageReviews: 4.2,
        availability: 'IN_STOCK',
        imageSrc: '/images/quinoa-seeds.jpg',
        isAddedToFav: false,
      },
    ],
  };

  constructor() {}

  getData(product: Object) {
    if (product === 'snacksNdMunchies') return this.snacksNdMunchies;
    else if (product == 'fruitsNdVegetables') return this.fruitsNdVegetables;
    else if (product == 'diaryProducts') return this.diaryProducts;
    else if (product == 'drinksNdJuices') return this.drinksNdJuices;
    else if (product === 'attaNdFlour') return this.attaNdFlour;
    else if (product === 'nutsNdSeeds') return this.nutsNdSeeds;
    else if (product === 'superFoods') return this.superFoods;
    else return this.fruitsNdVegetables;
  }
}
